library_app/urls.py
from django.urls import path
from . import views
# app name
app_name = "library_app"

urlpatterns = [
    path("index/", views.LibraryIndexView.as_view(), name="index"),
    path('home/', views.LibraryHomeView.as_view(),name="home"),
    path('login/', views.UserLoginView.as_view(),name="login"),
    path('logout/', views.UserLogoutView.as_view(),name="logout"),
    path('register/', views.RegisterUserView.as_view(),name="register"),
    path('librarybooks/',views.LibraryBooksListView.as_view(),name="librarybooks"),
    path('borrowbook/<slug:book_name>/', views.BorrowBookView.as_view(),name="borrowbook"),
    path('userbooks/', views.UserBooks,name="userbooks"),
    path('return/<int:pk>/', views.UserReturnBook, name="return"),
    path('staffregister/', views.StaffUserView.as_view(),name="staffregister"),
    # staff login url doesn't require because it's done by site user login view
    #path("staff/login/", views.StaffLoginView.as_view(), name="staff"),
    path('addbook/', views.StaffAddBooksView.as_view(),name="addbook"),
    path('duebookusers/', views.DueBookUsers.as_view(),name="duebookusers"),
    path('wishlist/', views.WishListView.as_view(),name="wishlist"),
    path('userwishbook/', views.UserWishedBookView.as_view(),name="userwishbook"),
]

library_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('library_app.urls')),
]

library_app/forms.py
from django.contrib.auth.forms import AuthenticationForm
from library_app.models import Library, LibraryUserModel, BookListModel
from crispy_forms.layout import Layout, Submit, Field, Row, Column
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from library_app.models import LibraryStaff
from django import forms


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'username'}),label="", max_length=100, required=True)
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={'placeholder': 'password'}))

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Row('username', css_class='col-md-14', placeholder="username"),
                Row('password', css_class='col-md-14', placeholder="Password"),
            )
        )
        self.helper.add_input(Submit('submit','login'))


class RegisterUSerForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'ConForm Password'}), label="Confirm password")

    class Meta:
        model = LibraryUserModel
        fields = ['username','password']
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'username'}),
        }

    def clean_password2(self):
        password = self.cleaned_data
        if password['password'] == password['password2']:
            return password['password2']
        else:
            raise forms.ValidationError('password does not match')

    def __init__(self, *args, **kwargs):
        super(RegisterUSerForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Row('username', css_class='col-md-3', placeholder="username"),
                Row('password', css_class='col-md-3', placeholder="Password"),
                Row('password2', css_class='col-md-3', placeholder="Password2"),
            )
        )
        self.helper.add_input(Submit('submit','Register'))

# class LibraryBorrowBookForm(forms.ModelForm):
#     user = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
#
#     class Meta:
#         model = Library
#         fields = ['book']
#         widgets = {
#             'book': forms.Select(attrs={'class': 'form-control'}),
#         }
#
#     def __init__(self, *args, **kwargs):
#         book = kwargs.pop('book_initial', None)
#         super(LibraryBorrowBookForm, self).__init__(*args, **kwargs)
#         if book:
#             self.fields['book'].initial = book


class LibraryBorrowBookForm(forms.Form):
    user = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'username', 'class': 'form-control'}))
    book = forms.ModelChoiceField(queryset=BookListModel.objects.all(), widget=forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        book = kwargs.pop('book_initial', None)
        super(LibraryBorrowBookForm, self).__init__(*args, **kwargs)
        if book:
            self.fields['book'].initial = book

#Normal User authentication is enough for login staff user
# class StaffLoginForm(AuthenticationForm):
#     username = forms.CharField(label='Username', max_length=254)
#     password = forms.CharField(label='Password', widget=forms.PasswordInput)

# Staff Model register form
class StaffUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = User
        fields = ["username","password"]

    def clean_password2(self):
        password = self.cleaned_data
        if password['password'] == password['password_confirm']:
            return password['password_confirm']
        else:
            raise forms.ValidationError('password does not match')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])  # This line hashes the password
        if commit:
            user.save()
            LibraryStaff.objects.create(user=user)
        return user

    def __init__(self, *args, **kwargs):
        super(StaffUserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Row('username', css_class='col-md-3', placeholder="username"),
                Row('password', css_class='col-md-3', placeholder="Password"),
                Row('password_confirm', css_class='col-md-3', placeholder="password_confirm"),
            )
        )
        self.helper.add_input(Submit('submit','Register'))


class AddBookForm(forms.ModelForm):
    class Meta:
        model = BookListModel
        fields = ["name","authors","publish_date","release_date","slug", "available"]

    def __init__(self,*args, **kwargs):
        super(AddBookForm,self).__init__(*args,**kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Row('name', css_class='col-md-3', placeholder="username"),
                Row('authors', css_class='col-md-3'),
                Row('publish_date', css_class='col-md-3'),
                Row('release_date', css_class='col-md-3'),
                Row('slug', css_class='col-md-3'),
                Row('available', css_class='col-md-3'),
            )
        )
        self.helper.add_input(Submit('submit','Register'))


class WishListForm(forms.Form):
    user_name = forms.CharField(max_length=100)
    book_name = forms.CharField(max_length=100)
    author = forms.CharField(max_length=50)
    publish_date = forms.DateField()

library_app/views.py
from .models import (
    BookListModel,
    Library,
    LibraryUserModel,
    LibraryStaff,
    WishListModel,
)
from .forms import (
    UserLoginForm,
    RegisterUSerForm,
    LibraryBorrowBookForm,
    StaffUserForm,
    AddBookForm,
    WishListForm
)
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, CreateView
from django.views.generic.list import ListView
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.db import IntegrityError
from datetime import datetime, timedelta
from django.contrib import messages
from django.views.generic import View
from django.urls import reverse
from django.db.models import Count
from django.db.models import Q
from datetime import date
from django.utils.text import slugify


class LibraryIndexView(ListView):
    template_name = "index.html"
    model = BookListModel
    context_object_name = "books"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_counts = Library.objects.values('book__name') \
                                     .annotate(count=Count('book')) \
                                     .order_by('-count')

        # Format data for Chart.js
        book_name = [book['book__name'] for book in book_counts]
        borrow_counts = [book['count'] for book in book_counts]

        context['book_name'] = book_name
        context['borrow_counts'] = borrow_counts
        return context


class LibraryHomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"

class UserLoginView(View):
    template_name = "login.html"
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, context={'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/index/')
            else:
                messages.error(request, "Invalid User Name Or Password!")
                return render(request, self.template_name, context={'form':form, 'message':messages})
        return render(request, self.template_name, context={'form': form})

class UserLogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('/login/')

class RegisterUserView(View):
    form_class = RegisterUSerForm
    template_name = 'register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name,{'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            login(request, user)
            return redirect('/index/')
        return render(request, self.template_name, {'form': form})

class BorrowBookView(PermissionRequiredMixin,FormView):
    model = Library
    template_name = "borrowbook.html"
    form_class = LibraryBorrowBookForm
    success_url = "/home/"
    permission_required = 'library_app.add_library'

    def handle_no_permission(self):
        return HttpResponseForbidden("You do not have permission to view this page.")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        self.book_name = self.kwargs.get('book_name')
        if self.book_name:
            self.book = get_object_or_404(BookListModel, slug=self.book_name)
            kwargs['book_initial'] = self.book
        return kwargs

    def form_valid(self, form):
        if not self.request.user.has_perm(self.permission_required):
            return HttpResponseForbidden("Staff users are not allowed to borrow books.")
        # Fetch the user from the form
        username = form.cleaned_data["user"]
        user = get_object_or_404(LibraryUserModel, username=username)
        # Check if the user can borrow more books
        if user.book_count >= user.max_books:
            messages.error(self.request, "Already borrowed the maximum number of books. Can't borrow more.")
            return self.form_invalid(form)
        # Create the Library record
        Library.objects.create(user=user, book=self.book, issued=True)
        # Update the user's book count
        user.book_count += 1
        user.save()
        return super().form_valid(form)

class LibraryBooksListView(LoginRequiredMixin, ListView):
    template_name = "librarybooks.html"
    model = BookListModel
    context_object_name = "books"

@login_required
def UserBooks(request):
    user = request.user
    issued_books = Library.objects.filter(user=user, issued=True)
    context = {'issued_books': issued_books}
    return render(request, 'returnbooks.html', context)


def get_default_event_date():
    return datetime.now().date() + timedelta(days=48)


@login_required
@permission_required('library_app.change_library')
def UserReturnBook(request, pk):
    if not request.user.has_perm('library_app.change_library'):
        return HttpResponseForbidden("Staff users are not allowed to return books.")
    book_record = get_object_or_404(Library, pk=pk, user=request.user)
    current_user = request.user
    user = get_object_or_404(LibraryUserModel, username=current_user)
    user.book_count -= 1
    user.save()
    #user returned book after due date
    book_record.returned_on = get_default_event_date()
    #user returned book on date
    #book_record.returned_on = datetime.now()
    book_record.issued = False
    book_record.save()
    return redirect('/userbooks/')

#staff login can be done by site user login view
# class StaffLoginView(FormView):
#     form_class = StaffLoginForm
#     template_name = 'loginstaff.html'
#     success_url = "/home/"# Change 'dashboard' to your desired URL name
#
#     def form_valid(self, form):
#         username = form.cleaned_data['username']
#         password = form.cleaned_data['password']
#         user = authenticate(self.request, username=username, password=password)
#         if user is not None:
#             login(self.request, user)
#             return super().form_valid(form)
#         else:
#             return self.form_invalid(form)


class StaffUserView(CreateView):
    model = LibraryStaff
    template_name = "staffregister.html"
    form_class = StaffUserForm
    success_url = "/home/"

    def form_valid(self, form):
        try:
            # Attempt to create a LibraryStaff instance
            return super().form_valid(form)
        except IntegrityError:
            # If a user with the same ID already exists, redirect to home or any appropriate URL
            return HttpResponseRedirect(reverse('home'))

class StaffAddBooksView(PermissionRequiredMixin, CreateView):
    template_name = "addbook.html"
    model = BookListModel
    success_url = "/index/"
    form_class = AddBookForm
    permission_required = 'library_app.add_booklistmodel'

    def handle_no_permission(self):
        return HttpResponseForbidden("You do not have permission to view this page.")

    def form_valid(self, form):
        form.save()
        return redirect('/librarybooks/')

class DueBookUsers(PermissionRequiredMixin, ListView):
    model = Library
    template_name = "duereturn_book_users.html"
    context_object_name = 'libraries'
    permission_required = 'library_app.view_library'


    def handle_no_permission(self):
        return HttpResponseForbidden("You do not have permission to view this page.")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        library_object = Library.objects.all()
        due_users = []

        for library_instance in library_object:
            if library_instance.returned_on and library_instance.return_date < library_instance.returned_on:
                rdate = (library_instance.returned_on - library_instance.return_date).days
                user = library_instance.user.username
                book = library_instance.book.name
                due_users.append({
                    'user': user,
                    'book': book,
                    'rdate': rdate,
                })
        context['due_users'] = due_users
        return context

class UserWishedBookView(FormView):
    template_name = "userwish.html"
    form_class = WishListForm
    success_url = "/home/"

    def form_valid(self, form):
        user_name = form.cleaned_data['user_name']
        book_name = form.cleaned_data['book_name']
        author = form.cleaned_data['author']
        publish_date = form.cleaned_data['publish_date']
        try:
            book = BookListModel.objects.get(name=book_name)
            if book.available:
                messages.error(self.request, "Already Exist, Borrow Book From Library Books! ")
                return self.form_invalid(form)
            WishListModel.objects.create(user_name=user_name, book_name=book_name, author=author,
                                         publish_date=publish_date)
            messages.success(self.request, "Book added to  wishlist successfully!")
            return super().form_valid(form)

        except:
            WishListModel.objects.create(user_name=user_name, book_name=book_name, author=author,
                                         publish_date=publish_date)
            messages.success(self.request, "Book added to  wishlist successfully!")

library_app/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
     <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB CDN-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.min.css" rel="stylesheet"/>

  <!------------------------- BORROWBOOK STYLE BLOCK TAG ------------------------->

    {% block borrowbookstyle %}{% endblock %}
  <!------------------------- HOME STYLE BLOCK TAG --------------------------->

    {% block homestyle  %} {% endblock %}
  <!------------------------- INDEX STYLE BLOCK TAG----------------------------->

    {% block indexstyle %}{% endblock %}
  <!------------------------- reyturnstyle STYLE BLOCK TAG----------------------------->

    {% block returnbookstyle %}{% endblock %}
  <!------------------------- LIBRARYBOOK STYLE  BLOCK TAG----------------------------->

    {% block librarybookstyle %}{% endblock %}
</head>
<body>
   <!-------------------------- MDN Navbar --------------------->

        <nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary" style="z-index: 1000;  position: sticky; top: 0;">
          <!-- Container wrapper -->
          <div class="container-fluid">
            <!-- Toggle button -->
            <button
              data-mdb-collapse-init
              class="navbar-toggler"
              type="button"
              data-mdb-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <i class="fas fa-bars"></i>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <!-- Navbar brand -->
              <a class="navbar-brand mt-2 mt-lg-0 text-gray" href="{% url 'library_app:index' %}" style="color:#6F4E37;">
                <h4> Hyderabad Library </h4>
              </a>
              <!-- Left links -->
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'library_app:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'library_app:staffregister' %}">Staff Register</a>
                </li>
                  <li class="nav-item">
                  <a class="nav-link" href="{% url 'library_app:userwishbook' %}">Order Book</a>
                </li>
              </ul>
            </div>
              {% if user.is_authenticated %}
            <div class="d-flex align-items-center">
              <!-- Login -->
             <div>
                 <a type="button" class="btn btn-primary me-3" href="{% url 'library_app:logout' %}">Logout</a>
             </div>
            </div>
              {% else %}
             <div class="d-flex align-items-center">
              <!-- Login -->
             <div>
                 <a type="button" class="btn btn-primary me-3" href="{% url 'library_app:login' %}">Login</a>
             </div>
            </div>
              {% endif %}
              <div class="me-3">
                 <a type="button" class="btn btn-warning" href="{% url 'library_app:librarybooks' %}">Borrow Book</a>
              </div>
              <div>
              {% if user.is_authenticated %}
               <span style="color:black;"><strong style="color:green;">Welcome</strong> {{ user.username }}</span>
              {% endif %}
              </div>
          </div>
           <div class="dropdown" style="margin-left:10px;">
                <a
                  data-mdb-dropdown-init
                  class="text-reset me-3 dropdown-toggle hidden-arrow"
                  href="#"
                  id="navbarDropdownMenuLink"
                  role="button"
                  aria-expanded="false"
                >
                  <i class="fas fa-bell"></i>
                  <span class="badge rounded-pill badge-notification bg-danger">1</span>
                </a>
                <ul
                  class="dropdown-menu dropdown-menu-end"
                  aria-labelledby="navbarDropdownMenuLink"
                >
                  <li>
                    <a class="dropdown-item" href="#">Some news</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#">Another news</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </li>
                </ul>
           </div>
          <!-- Avatar -->
          <div class="dropdown me-3">
            <a
              data-mdb-dropdown-init
              class="dropdown-toggle d-flex align-items-center hidden-arrow"
              href="#"
              id="navbarDropdownMenuAvatar"
              role="button"
              aria-expanded="false"
            >
              <img
                src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp"
                class="rounded-circle"
                height="25"
                alt="Black and White Portrait of a Man"
                loading="lazy"
              />
            </a>
            <ul
              class="dropdown-menu dropdown-menu-end"
              aria-labelledby="navbarDropdownMenuAvatar"
            >
              <li>
                <a class="dropdown-item" href="#">My profile</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Settings</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Logout</a>
              </li>
            </ul>
          </div>
        </nav>
    <!--------------------------- Side Bar ----------------------------------->

    <div class="container-fluid">
        {% block sidebar %}
        <!-- Default sidebar can be empty or contain common items -->
        {% endblock %}
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!--------------------------- MDN Script ------------------------->


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.umd.min.js">

</script>
</body>
</html>

library_app/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Dashboard{% endblock %}

{% block homestyle  %}
<style>
    body {
      background-color: #fbfbfb;
    }
    @media (min-width: 991.98px) {
      main {
        padding-left: 240px;
      }
    }

    /* Sidebar */
    .sidebar {
      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      padding: 58px 0 0; /* Height of navbar */
      box-shadow: 0 2px 5px 0 rgb(0 0 0 / 5%), 0 2px 10px 0 rgb(0 0 0 / 5%);
      width: 240px;
      z-index: 600;
      background-color: #DAC0A3;
    }

    @media (max-width: 991.98px) {
      .sidebar {
        width: 100%;
      }
    }
    .sidebar .active {
      border-radius: 5px;
      box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
    }

    .sidebar-sticky {
      position: relative;
      top: 0;
      height: calc(100vh - 48px);
      padding-top: 0.5rem;
      overflow-x: hidden;
      overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
    }
      .sidebar img {
        width: 100%;
        height: auto;
        display: block;
        margin: 0 auto;

    }
      .list-group-item {
      margin-bottom: 15px; /* Adjust the value as needed */
      padding-bottom: 10px; /* Adjust the value as needed */
    }
</style>

{% endblock %}

{% block sidebar %}
<!--Main Navigation-->
<header>
   <!-- Sidebar -->
  <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse ">
    <div class="position-sticky">
      <img src="{% static 'images/librarybackgroundimg.jpg' %}" alt="Sidebar Image">
      <div class="list-group list-group-flush mx-3 mt-4">
        <a
          href="{% url 'library_app:index'%}"
          class="list-group-item list-group-item-action py-2 ripple"
          aria-current="true"
        >
         <i class="fab fa-windows me-3"></i><span>Dashboard</span>
        </a>
        <a href="{% url 'library_app:librarybooks' %}" class="list-group-item list-group-item-action py-2 ripple {% if request.path == '/library_app:librarybooks/' %} class='active'{% endif %}"
          ><i class="fas fa-book me-3"></i><span>Borrow Book</span></a
        >
          <a href="{% url 'library_app:userbooks' %}" class="list-group-item list-group-item-action py-2 ripple  "
          ><i class="fas fa-arrow-rotate-left me-3"></i><span>Return Book</span></a
          >
        <a href="{% url 'library_app:addbook' %}" class="list-group-item list-group-item-action py-2 ripple "
          ><i class="fas fa-square-plus me-3"></i><span>Add Book</span></a
        >
        <a href="{% url 'library_app:duebookusers' %}" class="list-group-item list-group-item-action py-2 ripple"
          ><i class="far fa-calendar-minus me-3"></i><span>Books Due Users</span></a
        >
          <a href="{% url 'library_app:wishlist' %}" class="list-group-item list-group-item-action py-2 ripple"
          ><i class="far fa-bookmark me-3"></i><span>Wish List</span></a
        >
      </div>
    </div>
  </nav>
  <!-- Sidebar -->
</header>
<!--Main Navigation-->


{% endblock %}
{% block content %}
<div class="container text-center">
  {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }} </li>
                {% endfor %}
            </ul>
{% endif %}
</div>
<div class="container d-flex align-items-center justify-content-center" style="min-height: 90vh;">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-12 col-lg-12">
        <ul  class="list-group list-group-flush">
            <li class="list-group-item"><a href="{% url 'library_app:librarybooks' %}" style="color:#6F4E37 ; font-weight: bold; "><i class="fas fa-book-open me-3"></i>Borrow Book</a></li>
            <li class="list-group-item border-bottom"><a href="{% url 'library_app:userbooks' %}" style="color:#6F4E37 ; font-weight: bold;"><i class="fas fa-arrow-right-arrow-left me-3"></i>Return Book</a></li>
            <li class="list-group-item border-bottom"><a href="{% url 'library_app:addbook' %}" style="color:#6F4E37 ; font-weight: bold;"><i class="fas fa-book-medical me-3"></i>Add Book</a></li>
            <li class="list-group-item border-bottom"><a href="{% url 'library_app:duebookusers' %}" style="color:#6F4E37 ; font-weight: bold;"><i class="fas fa-user-large-slash me-3"></i>Book Due Users</a></li>
            <li class="list-group-item border-bottom"><a href="{% url 'library_app:wishlist' %}" style="color:#6F4E37 ; font-weight: bold;"><i class="fas fa-bookmark me-3"></i>Wish List</a></li>
        </ul>
      </div>
    </div>
</div>
{% endblock %}

library_app/templates/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Login</title>
       <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB CDN-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.min.css" rel="stylesheet"/>
</head>
<body>
<div class="row row-cols-1 row-cols-md-3 g-4" style="margin-top:50px; margin-left:100px">
   <div class="col">
      <div class="card h-100">
         <div class="card-body">
            <h1 class="card-title">Library User Login</h1>
              {% if messages %}
            <ul class="messages">
               {% for message in messages %}
               <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="color:red;">{{ message }}</li>
               {% endfor %}
            </ul>
            {% endif %}
            <div class="container">
               <form action="" method="post">
                  {% csrf_token %}
                  {% crispy form %}
               </form>
               <p>Don't have a Account? <a href="{% url 'library_app:register' %}">Register</a></p>
            </div>
         </div>
         <div class="card-footer">
            <small class="text-muted">Last updated 3 mins ago</small>
         </div>
      </div>
   </div>
</div>
<!------------------- MDB SCRIPT -------------------->

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.umd.min.js">
</script>
</body>
</html>